version: '3'

services:
  #Setting up my repository
  chfe:
    image: qutmotorsport/configapp-frontend:test
    container_name: cfh_frontend
    depends_on:
      - chbe
    expose:
      - "3000"
    ports:
      - "3000:3000"
  chbe:
    image: backend:dev
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cfh_backend
    entrypoint: src/entrypoint.sh
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    environment: # Needed to override some environment variables so that the backend uses docker volumes
      - DATABASE_URL=postgresql://admin:admin@db:5432/cfhub_db
      - SAVE_VOLUME=/var/lib/docker/volumes/qutms_configappbackend_log_storage/
      - DOCKER_ENV=True
    volumes:
      - log_storage:/var/lib/docker/volumes/qutms_configappbackend_log_storage/

    expose:
      - 5873
    #links:
    depends_on:
      - db
    ports: 
      - "5873:5873"
  db:
    image: postgres:12-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=cfhub_db

volumes:
  postgres_data:
  log_storage: