version: '3'

services:
  #Setting up my repository
  chfe:
    image: qutmotorsport/configapp-frontend:test
    #image: frontend:staging
    container_name: confighubfrontend
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    #links:
    depends_on:
      - chbe
    expose:
      - "3000"
    ports:
      - "3000:3000"
  chbe:
    image: qutmotorsport/configapp-backend
    #image: backend:staging
    container_name: confighubbackend
    environment:
      - FLASK_RUN_PORT=5873
      - FLASK_APP=src/main.py

    expose:
      - 5873
    #links:
    depends_on:
      - db
    ports: 
      - "5873:5873"
  db:
    image: postgres:12-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=cfhub_db

volumes:
  postgres_data: