version: '3'

services:
  #Setting up my repository
  chfe:
    image: qutmotorsport/configapp-frontend
    container_name: confighubfrontend
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    #links:
    depends_on:
      - chbe
    expose:
      - "3000"
    ports:
      - "3000:3000"
  chbe:
    image: qutmotorsport/configapp-backend
    container_name: confighubbackend
    environment:
      - DEBUG=True

    expose:
      - 5873
    #links:

    ports: 
      - "5873:5873"
