name: cfback

channels:
  - defaults
  - conda-forge
  - anaconda

#https://docs.conda.io/projects/conda/en/latest/user-guide/tasks/manage-environments.html#updating-an-environment

dependencies:
  - pip==20.2.4 #tool for installing Python packages
  - httptools==0.1.1 #Fast HTTP parser
  - numpy==1.19.2 #Array processing for numbers, strings, records, and objects.
  - h2==3.2.0
  - pylint==2.6.0 # for linting when you code
  - black==20.8b1 # for autoformatting (when you save)
  - werkzeug==1.0.1
  - flask==1.1.2
  - flask-sqlalchemy==2.4.4
  - flask-login==0.5.0
  - flask-wtf==0.14.3
  - flask-migrate==2.4.0
  - flask-cors==3.0.9
  - pandas
  - pip: 
    - flask-praetorian==1.1.0
    - psycopg2-binary==2.8.4
    - sqlathanor
    - gunicorn


# Environment must be recreated for variables to be set. Updating doesn't work
# The docker cache must also be cleared to make room for the new environment
variables:
  FLASK_APP: src/main.py
  FLASK_ENV: production
  FLASK_RUN_PORT: 5873
  SQL_HOST: db
  SQL_PORT: 5432
  DATABASE: postgres
